using System.ComponentModel.DataAnnotations;
using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Class service - inherits all CRUD operations from BaseService
/// Add class-specific business logic here
/// </summary>
public class ClassService : BaseService<Class>, IClassService
{
    protected override string EntityName => "Class";
    protected override string ApiEndpoint => "classes";

    public ClassService(ISpringApiClient springClient, ILogger<ClassService> logger)
        : base(springClient, logger)
    {
    }

    /// <summary>
    /// Create a new class using only required fields (ID is generated by backend)
    /// </summary>
    public async Task<Class> CreateAsync(CreateClassRequest request, CancellationToken ct = default)
    {
        if (request == null)
        {
            throw new ValidationException("Class data is required");
        }
        if (string.IsNullOrWhiteSpace(request.Name))
        {
            throw new ValidationException("Name is required");
        }
        if (request.CustomerId <= 0)
        {
            throw new ValidationException("Customer ID must be greater than 0");
        }

        try
        {
            // Send only the fields without ID to Spring Boot
            var created = await _springClient.PostAsync<CreateClassRequest, Class>(ApiEndpoint, request, ct);
            if (created == null)
            {
                throw new InvalidOperationException("Backend returned null when creating Class");
            }
            return ApplyBusinessLogic(created);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Spring Boot error while creating {EntityName}: {ex.Message}", ex);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Failed to create {EntityName}", ex);
        }
    }
    
     /// <summary>
    /// Get all classes for a specific customer
    /// Calls Spring Boot endpoint: GET /classes/customer/{customerId}
    /// </summary>
    public async Task<IEnumerable<Class>> GetByCustomerIdAsync(int customerId, CancellationToken ct = default)
    {
        if (customerId <= 0)
        {
            throw new ValidationException("Customer ID must be greater than 0");
        }

        try
        {
            var classes = await _springClient.GetAsync<IEnumerable<Class>>($"{ApiEndpoint}/customer/{customerId}", ct);
            return classes?.Select(c => ApplyBusinessLogic(c)) ?? Enumerable.Empty<Class>();
        }
        catch (HttpRequestException ex) when (ex.Message.Contains("404"))
        {
            _logger.LogWarning("No classes found for customer {CustomerId}", customerId);
            return Enumerable.Empty<Class>();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching classes for customer {CustomerId}", customerId);
            throw new InvalidOperationException($"Failed to fetch classes for customer from backend", ex);
        }
    }

    protected override Class ApplyBusinessLogic(Class classEntity)
    {
        // Add class-specific transformations here
        // For example: calculate available seats, check prerequisites
        if (!string.IsNullOrWhiteSpace(classEntity.Name))
        {
            classEntity.Name = classEntity.Name.Trim();
        }
        return classEntity;
    }

    /// <summary>
    /// Validate class data
    /// </summary>
    protected override void ValidateEntity(Class classEntity)
    {
        base.ValidateEntity(classEntity);
        if (string.IsNullOrWhiteSpace(classEntity.Name))
        {
            throw new ValidationException("Name is required");
        }
        if (classEntity.CustomerId <= 0)
        {
            throw new ValidationException("Customer ID must be greater than 0");
        }
    }
    
    public async Task<Class?> PatchAsync(int id, PatchClassRequest request, CancellationToken ct = default)
    {
        if (id <= 0)
            throw new ValidationException("Class ID must be greater than 0");
        
        if (request == null) 
            throw new ValidationException("Patch data is required");

        // Ensure at least one field is provided
        if (request.Name is null && request.CustomerId is null)
        {
            throw new ValidationException("At least one field (Name or CustomerId) must be provided for patch");
        }

        try
        {
            // Optionally verify existence
            var existing = await _springClient.GetAsync<Class>($"{ApiEndpoint}/{id}", ct);
            if (existing == null)
            {
                return null;
            }

            var updated = await _springClient.PatchAsync<PatchClassRequest, Class>($"{ApiEndpoint}/{id}", request, ct);
            
            if (updated == null)
            {
                throw new InvalidOperationException($"Backend returned null when patching {EntityName} {id}");
            }
            return ApplyBusinessLogic(updated);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while patching {EntityName} {Id}", EntityName, id);
            throw new InvalidOperationException($"Spring Boot error while patching {EntityName} {id}: {ex.Message}", ex);
        }
    }
}
