using Polly;
using System.ComponentModel.DataAnnotations;
using zoplannerservice.DTO.Responses;
using zoplannerservice.Models;


namespace zoplannerservice.Services;

/// <summary>
/// Consultant service - handles consultant business logic
/// </summary>


public class ConsultantService : BaseService<Consultant>, IConsultantService
{
    protected override string EntityName => "Consultant";
    protected override string ApiEndpoint => "consultants";

    public ConsultantService(ISpringApiClient springClient, ILogger<ConsultantService> logger)
        : base(springClient, logger)
    {
    }

    /// <summary>
    /// Apply consultant-specific business logic
    /// Add transformations when business requirements are defined
    /// </summary>
    protected override Consultant ApplyBusinessLogic(Consultant consultant)
    {
        // Add consultant-specific logic here when needed
        return consultant;
    }

    /// <summary>
    /// Create a new consultant using only required fields (ID is generated by backend)
    /// </summary>
    public async Task<Consultant> CreateAsync(CreateConsultantRequest request, CancellationToken ct = default)
    {
        if (request == null)
        {
            throw new ValidationException("Consultant data is required");
        }
        if (string.IsNullOrWhiteSpace(request.City))
        {
            throw new ValidationException("City is required");
        }
        if (request.UserId < 0)
        {
            throw new ValidationException("UserId is required");
        }
        if (request.ManagerId < 0)
        {
            throw new ValidationException("ManagerId is required");
        }


        try
        {
            // Send only the fields without ID to Spring Boot
            var created = await _springClient.PostAsync<CreateConsultantRequest, Consultant>(ApiEndpoint, request, ct);
            if (created == null)
            {
                throw new InvalidOperationException("Backend returned null when creating Consultant");
            }
            return ApplyBusinessLogic(created);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Spring Boot error while creating {EntityName}: {ex.Message}", ex);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Failed to create {EntityName}", ex);
        }
    }

    //Task<Consultant?> IBaseService<Consultant>.GetByIdAsync(long id, CancellationToken ct)
    //{
    //    throw new NotImplementedException();
    //}



    public Task<Consultant> CreateAsync(Consultant entity, CancellationToken ct = default)
    {
        throw new NotImplementedException();
    }

    public Task<Consultant?> UpdateAsync(int id, Consultant entity, CancellationToken ct = default)
    {
        throw new NotImplementedException();
    }


    // Behövs denna?
    /// <summary>
    /// Get user by username
    /// Calls Spring Boot endpoint: GET /users/username/{username}
    /// </summary>
    //public async Task<Consultant?> getbyusernameasync(string username, CancellationToken ct = default)
    //{
    //    if (string.IsNullOrWhiteSpace(username))
    //    {
    //        throw new ValidationException("username is required");
    //    }

    //    try
    //    {
    //        var user = await _springClient.GetAsync<Consultant>($"{ApiEndpoint}/username/{username}", ct);
    //        return user == null ? null : ApplyBusinessLogic(user);
    //    }
    //    catch (HttpRequestException ex) when (ex.Message.Contains("404"))
    //    {
    //        _logger.LogWarning("user with username {username} not found", username);
    //        return null;
    //    }
    //    catch (Exception ex)
    //    {
    //        _logger.LogError(ex, "error fetching {entityname} by username {username}", EntityName, username);
    //        throw new InvalidOperationException($"failed to fetch {EntityName} by username from backend", ex);
    //    }
    //}

    public async Task<ConsultantOverviewResponse> GetConsultantOverviewAsync(
            int consultantId,
            DateTime? from = null,
            DateTime? to = null)
    {
        var fromDate = from ?? DateTime.UtcNow.Date;
        var toDate = to ?? fromDate.AddDays(30);

        try
        {
            // 1) Get assignments (It already contain Course + Sessions)
            var assignments = await _springClient.GetAsync<List<Assignment>>("assignments");
            if (assignments == null)
            {
                throw new InvalidOperationException("Backend returned null assignments");
            }

            // 2) Only keep assignments for this consultant 
            var consultantAssignments = assignments
                .Where(a => a.ConsultantId == consultantId)
                .ToList();

            // 3) Build sessions from assignment.Sessions (flatten)
            //    and filter by from/to
            var sessionRows = consultantAssignments
                .Where(a => a.Sessions != null)
                .SelectMany(a => a.Sessions.Select(s => new { Assignment = a, Session = s }))
                .Where(x => x.Session.TimeStart >= fromDate && x.Session.TimeStart <= toDate)
                .ToList();

            // 4) ActiveCourses = courses that have sessions in the window
            var activeCourses = sessionRows
                .Where(x => x.Assignment.Course != null)
                .Select(x => x.Assignment.Course)
                .GroupBy(c => c.Id)
                .Select(g => g.First())
                .Select(c => new ActiveCourseDto
                {
                    CourseId = c.Id,
                    Name = c.Name,
                    DateStart = c.DateStart,
                    DateEnd = c.DateEnd
                })
                .ToList();

            // 5) Map sessions to DTO (we know assignment + course here)
            var sessionDtos = sessionRows
                .Where(x => x.Assignment.Course != null)
                .Select(x => new SessionDto
                {
                    SessionId = (int)x.Session.Id,
                    TimeStart = x.Session.TimeStart,
                    TimeEnd = x.Session.TimeEnd,
                    Location = x.Session.Location.ToString(),
                    Comment = x.Session.Comment,
                    AssignmentId = (int)x.Assignment.Id,
                    CourseId = (int)x.Assignment.Course.Id,
                    CourseName = x.Assignment.Course.Name
                })
                .ToList();

            return new ConsultantOverviewResponse
            {
                ConsultantId = consultantId,
                ActiveCourses = activeCourses,
                Sessions = sessionDtos
            };
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while fetching consultant overview");
            throw new InvalidOperationException("Failed to fetch consultant overview from backend", ex);
        }
    }


}


