using System.ComponentModel.DataAnnotations;
using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Customer service with specific business logic
/// Inherits common CRUD operations from BaseService
/// </summary>
public class CustomerService : BaseService<Customer>, ICustomerService
{
    protected override string EntityName => "Customer";
    protected override string ApiEndpoint => "customers";

    public CustomerService(ISpringApiClient springClient, ILogger<CustomerService> logger)
        : base(springClient, logger)
    {
    }

    /// <summary>
    /// Create a new customer using only Name and City (ID is generated by backend)
    /// </summary>
    public async Task<Customer> CreateAsync(CreateCustomerRequest request, CancellationToken ct = default)
    {
        if (request == null)
        {
            throw new ValidationException("Customer data is required");
        }
        if (string.IsNullOrWhiteSpace(request.Name))
        {
            throw new ValidationException("Name is required");
        }
        if (string.IsNullOrWhiteSpace(request.City))
        {
            throw new ValidationException("City is required");
        }

        try
        {
            // Spring Boot uses @RequestParam, so we need to send form data instead of JSON
            var formData = new Dictionary<string, string>
            {
                { "name", request.Name },
                { "city", request.City }
            };
            
            var created = await _springClient.PostFormAsync<Customer>(ApiEndpoint, formData, ct);
            if (created == null)
            {
                throw new InvalidOperationException("Backend returned null when creating Customer");
            }
            return ApplyBusinessLogic(created);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Spring Boot error while creating {EntityName}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Partially update a customer using PATCH semantics
    /// </summary>
    public async Task<Customer?> PatchAsync(int id, PatchCustomerRequest request, CancellationToken ct = default)
    {
        if (id <= 0) throw new ValidationException("Customer ID must be greater than 0");
        if (request == null) throw new ValidationException("Patch data is required");

        // Ensure at least one field is provided
        if (request.Name is null && request.City is null)
        {
            throw new ValidationException("At least one field (Name or City) must be provided for patch");
        }

        try
        {
            // Optionally verify existence
            var existing = await _springClient.GetAsync<Customer>($"{ApiEndpoint}/{id}", ct);
            if (existing == null)
            {
                return null;
            }

            var updated = await _springClient.PatchAsync<PatchCustomerRequest, Customer>($"{ApiEndpoint}/{id}", request, ct);
            if (updated == null)
            {
                throw new InvalidOperationException($"Backend returned null when patching {EntityName} {id}");
            }
            return ApplyBusinessLogic(updated);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while patching {EntityName} {Id}", EntityName, id);
            throw new InvalidOperationException($"Spring Boot error while patching {EntityName} {id}: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// Apply customer-specific business logic
    /// Override to add custom transformations or calculations
    /// </summary>
    protected override Customer ApplyBusinessLogic(Customer customer)
    {
        // Example: Normalize customer name
        if (!string.IsNullOrWhiteSpace(customer.Name))
        {
            customer.Name = customer.Name.Trim();
        }
        return customer;
    }

    /// <summary>
    /// Validate customer data
    /// </summary>
    protected override void ValidateEntity(Customer customer)
    {
        base.ValidateEntity(customer);
        if (string.IsNullOrWhiteSpace(customer.Name))
        {
            throw new ValidationException("Name is required");
        }
        if (string.IsNullOrWhiteSpace(customer.City))
        {
            throw new ValidationException("City is required");
        }
    }
}

