using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Interface for Class service operations
/// </summary>
public interface IClassService : IBaseService<Class>
{
    /// <summary>
    /// Create a new class using only required fields (ID is generated by backend)
    /// </summary>
    Task<Class> CreateAsync(CreateClassRequest request, CancellationToken ct = default);
    
    /// <summary>
    /// Get all classes for a specific customer
    /// Calls Spring Boot endpoint: GET /classes/customer/{customerId}
    /// </summary>
    Task<IEnumerable<Class>> GetByCustomerIdAsync(int customerId, CancellationToken ct = default);
}