using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Consultant service interface - extends base service with user-specific operations
/// </summary>
public interface IConsultantService : IBaseService<Consultant>
{
    /// <summary>
    /// Create a new consultant using only required fields (ID is generated by database)
    /// </summary>
    Task<Consultant> CreateAsync(CreateConsultantRequest request, CancellationToken ct = default);

    /// <summary>
    /// Get user by username
    /// </summary>
}
