using zoplannerservice.Models;
using System.ComponentModel.DataAnnotations;


namespace zoplannerservice.Services;

/// <summary>
/// Manager service - handles manager business logic
/// </summary>


public class ManagerService : BaseService<Manager>, IManagerService
{
    protected override string EntityName => "Manager";
    protected override string ApiEndpoint => "managers";

    public ManagerService(ISpringApiClient springClient, ILogger<ManagerService> logger)
        : base(springClient, logger)
    {
    }

    /// <summary>
    /// Apply manager-specific business logic
    /// Add transformations when business requirements are defined
    /// </summary>
    protected override Manager ApplyBusinessLogic(Manager manager)
    {
        // Add manager-specific logic here when needed
        return manager;
    }

    /// <summary>
    /// Create a new manager using only required fields (ID is generated by backend)
    /// </summary>
    public async Task<Manager> CreateAsync(int userId, CancellationToken ct = default)
    {
        if (userId < 0)
        {
            throw new ValidationException("UserId is required");
        }



        try
        {
            // Send only the fields without ID to Spring Boot
            var created = await _springClient.PostAsync<Manager>($"{ApiEndpoint}?userId={userId}");
            if (created == null)
            {
                throw new InvalidOperationException("Backend returned null when creating Manager");
            }
            return ApplyBusinessLogic(created);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Spring Boot error while creating {EntityName}: {ex.Message}", ex);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Failed to create {EntityName}", ex);
        }
    }



    //Task<Manager?> IBaseService<Manager>.GetByIdAsync(long id, CancellationToken ct)
    //{
    //    throw new NotImplementedException();
    //}

    




    // Behövs denna?
    /// <summary>
    /// Get user by username
    /// Calls Spring Boot endpoint: GET /users/username/{username}
    /// </summary>
    //public async Task<Manager?> getbyusernameasync(string username, CancellationToken ct = default)
    //{
    //    if (string.IsNullOrWhiteSpace(username))
    //    {
    //        throw new ValidationException("username is required");
    //    }

    //    try
    //    {
    //        var user = await _springClient.GetAsync<Manager>($"{ApiEndpoint}/username/{username}", ct);
    //        return user == null ? null : ApplyBusinessLogic(user);
    //    }
    //    catch (HttpRequestException ex) when (ex.Message.Contains("404"))
    //    {
    //        _logger.LogWarning("user with username {username} not found", username);
    //        return null;
    //    }
    //    catch (Exception ex)
    //    {
    //        _logger.LogError(ex, "error fetching {entityname} by username {username}", EntityName, username);
    //        throw new InvalidOperationException($"failed to fetch {EntityName} by username from backend", ex);
    //    }
    //}
}
