using zoplannerservice.Models;
using System.ComponentModel.DataAnnotations;

namespace zoplannerservice.Services;

/// <summary>
/// User service - handles user business logic
/// Implements full CRUD operations plus username lookup
/// </summary>

// TODO: Implement method GetUsersByRole

public class UserService : BaseService<User>, IUserService
{
    protected override string EntityName => "User";
    protected override string ApiEndpoint => "users";

    public UserService(ISpringApiClient springClient, ILogger<UserService> logger)
        : base(springClient, logger)
    {
    }

    /// <summary>
    /// Apply user-specific business logic
    /// Add transformations when business requirements are defined
    /// </summary>
    protected override User ApplyBusinessLogic(User user)
    {
        // Add user-specific logic here when needed
        return user;
    }

    /// <summary>
    /// Create a new user using only required fields (ID is generated by backend)
    /// </summary>
    public async Task<User> CreateAsync(CreateUserRequest request, CancellationToken ct = default)
    {
        if (request == null)
        {
            throw new ValidationException("User data is required");
        }
        if (string.IsNullOrWhiteSpace(request.Username))
        {
            throw new ValidationException("Username is required");
        }
        if (string.IsNullOrWhiteSpace(request.Email))
        {
            throw new ValidationException("Email is required");
        }
        if (string.IsNullOrWhiteSpace(request.Password))
        {
            throw new ValidationException("Password is required");
        }
        if (request.Role == null)
        {
            throw new ValidationException("Role is required");
        }
        if (string.IsNullOrWhiteSpace(request.City))
        {
            throw new ValidationException("City is required");
        }
        if (string.IsNullOrWhiteSpace(request.Name))
        {
            throw new ValidationException("Name is required");
        }

        try
        {
            // Send only the fields without ID to Spring Boot
            var created = await _springClient.PostAsync<CreateUserRequest, User>(ApiEndpoint, request, ct);
            if (created == null)
            {
                throw new InvalidOperationException("Backend returned null when creating User");
            }
            return ApplyBusinessLogic(created);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogError(ex, "Spring Boot error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Spring Boot error while creating {EntityName}: {ex.Message}", ex);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unexpected error while creating {EntityName}", EntityName);
            throw new InvalidOperationException($"Failed to create {EntityName}", ex);
        }
    }

    /// <summary>
    /// Get user by username
    /// Calls Spring Boot endpoint: GET /users/username/{username}
    /// </summary>
    public async Task<User?> GetByUsernameAsync(string username, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(username))
        {
            throw new ValidationException("Username is required");
        }

        try
        {
            var user = await _springClient.GetAsync<User>($"{ApiEndpoint}/username/{username}", ct);
            return user == null ? null : ApplyBusinessLogic(user);
        }
        catch (HttpRequestException ex) when (ex.Message.Contains("404"))
        {
            _logger.LogWarning("User with username {Username} not found", username);
            return null;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching {EntityName} by username {Username}", EntityName, username);
            throw new InvalidOperationException($"Failed to fetch {EntityName} by username from backend", ex);
        }
    }
}
