using System.ComponentModel.DataAnnotations;

namespace zoplannerservice.Models;

/// <summary>
/// DTO for creating a new user (without ID - generated by database)
/// </summary>
public class CreateUserRequest
{
    [Required(ErrorMessage = "Username is required")]
    [MaxLength(200)]
    public string Username { get; set; } = string.Empty;

    [Required(ErrorMessage = "Password is required")]
    [MaxLength(200)]
    public string Password { get; set; } = string.Empty;

    [Required(ErrorMessage = "Role is required")]
    [MaxLength(100)]
    public string Role { get; set; } = string.Empty;

    [Required(ErrorMessage = "City is required")]
    [MaxLength(200)]
    public string City { get; set; } = string.Empty;

    [Required(ErrorMessage = "Name is required")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;
}
