using System.ComponentModel.DataAnnotations;

namespace zoplannerservice.Models;

/// <summary>
/// DTO for creating a new Customer. ID is generated by the backend.
/// Only Name and City are sent.
/// </summary>
public class CreateCustomerRequest
{
    [Required]
    public string Name { get; set; } = "";

    public string? City { get; set; }

    [Required]
    public long ManagerId { get; set; }
}
