using System.ComponentModel.DataAnnotations;

namespace zoplannerservice.Models;

/// <summary>
/// DTO for creating a new Class. ID is generated by the backend.
/// Only Name and CustomerId are sent.
/// </summary>
public class CreateClassRequest
{
    [Required(ErrorMessage = "Name is required")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [Required(ErrorMessage = "Customer ID is required")]
    public int CustomerId { get; set; }
}