using System.ComponentModel.DataAnnotations;
using zoplannerservice.Enums.UserRole;

namespace zoplannerservice.Models;

/// <summary>
/// DTO for creating a new user (without ID - generated by database)
/// </summary>
public class CreateUserRequest
{
    [Required(ErrorMessage = "Username is required")]
    [MaxLength(200)]
    public string Username { get; set; } = string.Empty;
    [Required(ErrorMessage = "Email is required")]
    [EmailAddress]
    [MaxLength(200)]
    public string Email { get; set; } = string.Empty;

    [Required(ErrorMessage = "Password is required")]
    [MaxLength(200)]
    public string Password { get; set; } = string.Empty;

    [Required(ErrorMessage = "Role is required")]
    public UserRole? Role { get; set; }

    [Required(ErrorMessage = "City is required")]
    [MaxLength(200)]
    public string City { get; set; } = string.Empty;

    [Required(ErrorMessage = "Name is required")]
    [MaxLength(200)]
    public string Name { get; set; } = string.Empty;
}
