using zoplannerservice.DTO.Responses;
using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Consultant service interface - extends base service with user-specific operations
/// </summary>
public interface IConsultantService : IBaseService<Consultant>
{
    /// <summary>
    /// Create a new consultant using only required fields (ID is generated by database)
    /// </summary>
    Task<Consultant> CreateAsync(CreateConsultantRequest request, CancellationToken ct = default);

    /// <summary>
    /// Get user by username
    /// </summary>


    Task<ConsultantOverviewResponse> GetConsultantOverviewAsync(
    int consultantId,
    DateTime? from = null,
    DateTime? to = null
);

    Task<List<ScheduleSearchRowDto>> SearchScheduleAsync(
    long? consultantId = null,
    long? courseId = null,
    string? city = null,
    string? location = null,
    DateTime? from = null,
    DateTime? to = null
);

}

