using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// Manager service interface - extends base service with manager-specific operations
/// </summary>
public interface IManagerService : IBaseService<Manager>
{
    /// <summary>
    /// Create a new manager using only required fields (ID is generated by database)
    /// </summary>
    Task<Manager> CreateAsync(int userId, CancellationToken ct = default);
}
