using zoplannerservice.DTO.Responses;
using zoplannerservice.Models;

namespace zoplannerservice.Services;

/// <summary>
/// User service interface - extends base service with user-specific operations
/// </summary>
public interface IUserService : IBaseService<User>
{
    /// <summary>
    /// Create a new user using only required fields (ID is generated by database)
    /// </summary>
    Task<User> CreateAsync(CreateUserRequest request, CancellationToken ct = default);

    /// <summary>
    /// Get user by username
    /// </summary>
    Task<User?> GetByUsernameAsync(string username, CancellationToken ct = default);

    Task<ProfilePictureResponseDto> UploadProfilePictureAsync(long id,IFormFile file,CancellationToken ct = default);
}
